first version of the album end point
glaubernespoli/dci-final-project-frontend pull request #69
Opened 2021-06-15 07:18 UTC by santiagoejm

2021-06-15 09:24 UTC, glaubernespoli requested changes
dont disable the eslint validations

2021-06-15 09:37 UTC, glaubernespoli commented on frontend/src/Routing/Routing.jsx
> +import AlbumEndPointPage from '../containers/pages/AlbumEndPointPage';
rename this to a proper name

2021-06-15 09:38 UTC, glaubernespoli commented on frontend/.eslintrc
> +    "react/prop-types": "off"
dont disable code validations

2021-06-15 09:41 UTC, glaubernespoli commented on frontend/src/containers/AlbumEndPoint/AlbumEndPoint.jsx
> +const AlbumEndPoint = () => {
rename this to RecordItem

2021-06-15 09:41 UTC, glaubernespoli commented on frontend/src/Routing/routes.js
> +export const AlbumEndPointRoute = '/albumendpoint';
rename both the variable and the endpoint

RecordRoute = '/record/'

2021-06-15 09:43 UTC, glaubernespoli commented on frontend/src/Routing/routes.js
> +export const AlbumEndPointRoute = '/albumendpoint';
you could also make it a function:

export const RecordRoute = id => '/record/' + id;

then you use it like

`history.push(RecordRoute(item.id));`

2021-06-16 07:27 UTC, Manonmani-s approved these changes, later dismissed
Ok

2021-06-16 09:37 UTC, glaubernespoli approved these changes

2021-06-16 09:37 UTC, merged