bugs fixed on grid properties, props validation, and myProvider.
glaubernespoli/dci-final-project-frontend pull request #77
Opened 2021-06-21 11:29 UTC by santiagoejm

2021-06-21 11:34 UTC, santiagoejm commented
Not sure, if the solution of the bug on MyProvider is the most elegant, there are no more errors displayed in the console, but still appears to be 2 unsolved issues, which I can not  access inspecting the browser.

Let me know, what do you think

2021-06-22 11:56 UTC, glaubernespoli requested changes
Check requested changes;
also do pull of the main to your local branch to solve conflicts before the pull request

2021-06-22 11:56 UTC, glaubernespoli commented on frontend/.env.development
> +REACT_APP_SERVER_URL=http://localhost:5000
do the merge; you should get a conflict here

2021-06-22 11:56 UTC, glaubernespoli commented on frontend/.env.development
> +REACT_APP_SERVER_URL=http://localhost:5000
(maybe)

2021-06-22 11:56 UTC, glaubernespoli commented on frontend/src/containers/Home/product-list/ProductItem.jsx
> +  item: PropTypes.objectOf(PropTypes.oneOfType([PropTypes.number, PropTypes.string]))
this should be string only. when we start taking the info from the backend we'll have strings as ids, not number. reason you're getting numbers also is probably due to the static file having different types for ids

2021-06-23 07:35 UTC, glaubernespoli approved these changes

2021-06-23 07:35 UTC, merged