updated carousel, receiving dynamic data, and hover effect on it and item list
glaubernespoli/dci-final-project-frontend pull request #84
Opened 2021-07-02 10:17 UTC by santiagoejm

2021-07-02 12:04 UTC, arifur-ra approved these changes, later dismissed
Done, Everything looks fine

2021-07-02 14:10 UTC, glaubernespoli requested changes

2021-07-02 14:10 UTC, glaubernespoli commented on frontend/src/containers/Home/carousel/Carousele.jsx
> +              // eslint-disable-next-line no-underscore-dangle
this line is not needed with the rule for _id disabled

2021-07-02 14:10 UTC, glaubernespoli commented on frontend/src/containers/Home/carousel/Item.jsx
> +    // eslint-disable-next-line no-underscore-dangle
same here

2021-07-02 14:10 UTC, glaubernespoli commented on frontend/src/containers/Home/carousel/Carousele.jsx
> +  const { data, error, isLoading } = useAxios('get', '/record');
still using the wrong endpoint to capture the records, should be /record/hot

2021-07-02 14:10 UTC, glaubernespoli commented on frontend/src/containers/Home/carousel/Carousele.jsx
> +        <Grid item xs={12}>
as shown, gris and paper not needed

2021-07-02 14:10 UTC, glaubernespoli commented on frontend/src/containers/Home/carousel/Item.jsx
> +  const { setItem } = context;
as we spoke, context is being set here and not used. delete

2021-07-02 14:10 UTC, glaubernespoli commented on frontend/src/containers/Home/carousel/Item.jsx
> +    setItem(item);
delete

2021-07-05 14:09 UTC, glaubernespoli approved these changes
(Y)

2021-07-05 14:09 UTC, merged

2022-02-24 16:27 UTC, glaubernespoli reviewed
fhjfghj

2022-02-24 19:18 UTC, Manonmani-s commented
> fhjfghj

Glauber, happy to see the review.